### ISSUE TITLE
With malformed input: Unix error: Success

### ISSUE THREAD

**Issue by The-Compiler** [drbig/snb#11]
When doing `snb file.md` where the file contains `foo`:

```
ERROR: Malformed input at line 1.
Unix error: Success
```

The first error makes sense, I don't think the second one does :wink:

**Comment by drbig** [comment]
I _think_ that's because it's easier to handle errors that way. But perhaps could be as simple as suppressing `Unix error` output on `Success` :)

**Comment by drbig** [comment]
Indeed. Should be fixed. Hopefully correctly...
