### ISSUE TITLE
todo list mode

### ISSUE THREAD

**Issue by The-Compiler** [drbig/snb#12]
I miss the todo list mode from hnb :wink:

![screenshot1](https://cloud.githubusercontent.com/assets/625793/11208758/40a5867a-8d1d-11e5-8863-7bef761feae3.png)

**Comment by drbig** [comment]
There is a todo mode - you can "cross out" items - it makes them darker. You can also highlight items (makes them brighter/bold). Didn't want to go with the trouble of adding `[X]` etc. And _I_ find the color/font-coding actually more readable.

**Comment by drbig** [comment]
(Will close. But ideas/feedback etc. are always welcome)

**Comment by The-Compiler** [comment]
Yup, I actually discovered that after opening this issue, this works for me right now.

Seems to work fine other than the issues I opened so far! :+1:

**Comment by drbig** [comment]
Feel free to PR stuff on the other issues. Don't think I'll be coding snb any time soon...

**Comment by The-Compiler** [comment]
My backlog of PRs I want to do is unfortunately bigger than available time - but it's on my looong TODO list :wink: Thanks for the work so far! Seems like a good `hnb` replacement.

**Comment by drbig** [comment]
Understandable. And thanks! I'm positively surprised that it's usable enough to not be another `just-for-me` project ;)
